site_name: "TechDocs Sample"
site_description: "Sample documentation generated for Backstage TechDocs"
site_author: "Your Name"
docs_dir: docs   # src/docs 以下の Markdown を使用
site_dir: ../../docs # 出力先（リポジトリルートの docs/）　

plugins:
  - techdocs-core
markdown_extensions:
  - toc
  - tables
  - fenced_code

theme:
  name: mkdocs

nav:
  - Home: index.md
