site_name: "TechDocs Sample"
site_description: "Sample documentation generated for Backstage TechDocs"
site_author: "Your Name"
docs_dir: .
site_dir: docs

plugins:
  - techdocs-core
markdown_extensions:
  - toc
  - tables
  - fenced_code

theme:
  name: mkdocs

nav:
  - Home: index.md
