name: Generate TechDocs

on:
  push:
    branches: [ main ]
    paths:
      - 'src/docs/**'
      - 'src/mkdocs.yml'

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      #
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: npx techdocs-cli generate --source-dir ./src --output-dir ./docs --no-docker --verbose

      - name: Commit generated docs
        run: |
          git config --local user.email "satou@aimsys.co.jp"
          git config --local user.name "shouji-satou"
          git add docs
          git commit -m "Update TechDocs" || echo "No changes"
          git push
